### ISSUE TITLE
query: is not a valid json string

### ISSUE THREAD

**Issue by saurav-milestone** [nikhilbadyal/esxport#48]
I am getting the following exception when firing this command

`esxport -q '{"query": {"match_all": {}}}' -i index_name -o index_name.csv`

Error: `Error: Invalid value for '-q' / '--query': '{query: is not a valid json string, caused Expecting value: line 1 column 1 (char 0)`

What am I doing wrong?

**Comment by saurav-milestone** [comment]
![image](https://github.com/nikhilbadyal/esxport/assets/126774607/d0428ff0-7145-4025-adc5-caf6cedeb9ba)

**Comment by nikhilbadyal** [comment]
Strange. Works fine for me. 
<img width="962" alt="image" src="https://github.com/nikhilbadyal/esxport/assets/59223300/c2d33e75-c418-4692-9244-bfaa4f64b84d">

Something related to windows. 

Do you have wsl , git or msys2 installed ? Can try in those terminal instead of windows CMD.

**Comment by nikhilbadyal** [comment]
Closing as no additional info was received.
